# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# This is a basic workflow to help you get started with Actions

name: Node JS build test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch

  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: ' Step 2: Create .env file'
      run: |
        touch .env
        echo ENVIRONMENT=${{ secrets.ENVIRONMENT }} >> .env
        echo HOSTNAME=${{ secrets.HOSTNAME }} >> .env
        echo PORT=${{ secrets.PORT }} >> .env
        echo DATABASE=${{ secrets.DATABASE }} >> .env
        echo DBUSER=${{ secrets.DBUSER }} >> .env
        echo DBPASSWORD=${{ secrets.DBPASSWORD }} >> .env
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm test